// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CandidateEvent {
    #[prost(string, tag="1")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(uint64, tag="3")]
    pub log_index: u64,
    #[prost(string, tag="4")]
    pub contract_address: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub event_signature: ::prost::alloc::string::String,
    /// "Transfer","Approval","Swap","Permit","FlashLoan"
    #[prost(string, tag="6")]
    pub event_type: ::prost::alloc::string::String,
    /// optional JSON string (topics, data)
    #[prost(string, tag="7")]
    pub metadata: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CandidateEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<CandidateEvent>,
}
// @@protoc_insertion_point(module)
