version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node:v0.24.0
    container_name: graph-node
    ports:
      - "8000:8000"  # GraphQL endpoint
      - "8020:8020"  # Ethereum JSON-RPC endpoint
    environment:
      - ETHEREUM_RPC_URL=http://127.0.0.1:8545/ # Your local Hardhat node URL
      - IPFS_API_URL=http://localhost:5001
      - POSTGRES_USER=graph
      - POSTGRES_PASSWORD=graph
      - POSTGRES_DB=graph-node
    depends_on:
      - ipfs
      - postgres

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    ports:
      - "5001:5001"
      - "8545:8545"

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: graph
      POSTGRES_DB: graph-node
    ports:
      - "5432:5432"
